### ISSUE TITLE
怎么什么都未显示？我确实下载了一些图片到~/BeautifulAlbum/album/cutecy目录

### ISSUE THREAD

**Issue by luckypoemster** [acane77/BeautifulAlbum#4]
hi.

12799@DESKTOP-B6LK9IO MINGW64 ~/BeautifulAlbum/dist (master)
$ ls
css/              icon-256x256.png  index.html
favicon.ico       icon-384x384.png  js/
icon-192x192.png  icon-512x512.png  manifest.webmanifest

12799@DESKTOP-B6LK9IO MINGW64 ~/BeautifulAlbum/dist (master)
$ cd ..

12799@DESKTOP-B6LK9IO MINGW64 ~/BeautifulAlbum (master)
$ ls
LICENSE          bootstrap.sh*  package-lock.json  scripts/
README.md        dist/          package.json       src/
album/           docs/          pnpm-lock.yaml     third_party/
babel.config.js  node_modules/  public/            vue.config.js

12799@DESKTOP-B6LK9IO MINGW64 ~/BeautifulAlbum (master)
$ cd album

12799@DESKTOP-B6LK9IO MINGW64 ~/BeautifulAlbum/album (master)
$ ls
cutecy/  cutecy.txt

12799@DESKTOP-B6LK9IO MINGW64 ~/BeautifulAlbum/album (master)
$ cd cutecy

12799@DESKTOP-B6LK9IO MINGW64 ~/BeautifulAlbum/album/cutecy (master)
$ ls
29F350F831E4B4B81A2A1317B580956DD79257CF_size351_w854_h1280.jpg
46D4B79EC452F0EE6889E543C689ABC8FB9B24A5_size256_w851_h1280.jpg
81967DD08014D49C3047F297C3508C073B973F00_size366_w853_h1280.jpg
887AEB157FD02AD8458154473A405FF0542EE6CD_size143_w853_h1280.jpg
8FC13125C4B921C29C388D3D8174988BEC99DB82_size61_w851_h1280.jpg
F206D750617FC4E94ED9A8788DBD4DC2E6539180_size198_w854_h1280.jpg

12799@DESKTOP-B6LK9IO MINGW64 ~/BeautifulAlbum/album/cutecy (master)
$

怎么回事？如何修复？
谢谢你

**Comment by luckypoemster** [comment]
<img width="958" alt="snap" src="https://github.com/user-attachments/assets/cc2801d8-a70f-48d2-8d3c-ef079f23e8c0">

**Comment by mmdjiji** [comment]
请仔细阅读使用说明，在build完将`api`目录放入`dist/`中

**Comment by mmdjiji** [comment]
如果实在不会用可以考虑我fork的分支，https://github.com/mmdjiji/iAlbum

**Comment by acane77** [comment]
用这个命令

```
./bootstrap.sh --prefix=~/BeautifulAlbum/install --album-dir=~/BeautifulAlbum/album --password=1234
```

`~/BeautifulAlbum/install` 是生成的目标目录，确保npm和python依赖都正确安装，并且运行命令没有任何报错，在生成之后确保`~/BeautifulAlbum/install`目录有api目录。

如果没有使用脚本build，自己用 generate_api.py 生成内容的话，参考文档的用法生成api，把生成的api手动放到dist目录。
